-- Template: Change a user's password
-- 
-- STEP 1: Generate the hash
-- Run in terminal: npm run change-password <username> <new-password>
-- Example: npm run change-password Gohan MyNewPassword123@
--
-- STEP 2: Copy the generated SQL UPDATE statement and run it here
--
-- STEP 3: The user can now login with the new password

-- Example (replace with the hash generated by the script):
-- UPDATE users
-- SET password_hash = '$2a$10$YOUR_GENERATED_HASH_HERE'
-- WHERE username = 'Gohan';

